site_name: مستندات شبیه‌ساز زمان‌بندی وظایف 🚀
site_description: شبیه‌ساز هوشمند زمان‌بندی و مدیریت تسک‌ها با پایتون

theme:
  name: material
  language: fa
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: teal
      toggle:
        icon: material/brightness-7
        name: تغییر به حالت تاریک
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: teal
      toggle:
        icon: material/brightness-4
        name: تغییر به حالت روشن

  font:
    text: Vazirmatn
    code: Roboto Mono

# تنظیمات الحاقیات اصلی متن
markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:pymdownx.emoji.twemoji
      emoji_generator: !!python/name:pymdownx.emoji.to_svg

# رفع قطعی مشکل آدرس‌دهی ماژول‌ها در پایتون
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [".", "models"] # اضافه شدن مسیر مستقیم پوشه مدل‌ها
          options:
            show_source: true
            show_root_heading: true
            show_root_toc_entry: true

extra_css:
  - https://fonts.googleapis.com/css2?family=Vazirmatn:wght@300;400;700&display=swap

# منوی ناوبری سایت
nav:
  - خانه: index.md
  - ارائه: presentation.md
  - مستندات فنی کد: simulation.md